import {mkdtemp,cp,rm,readFile,writeFile} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('..',import.meta.url));
const staging=await mkdtemp(path.join(os.tmpdir(),'localdocs-package-'));
const folder=path.join(staging,'本地文档-0.2.0');
await cp(path.join(root,'dist/本地文档.app'),path.join(folder,'本地文档.app'),{recursive:true});
await cp(path.join(root,'dist/chrome-extension-0.2.0'),path.join(folder,'chrome-extension-0.2.0'),{recursive:true});
await cp(path.join(root,'dist/开始使用-0.2.0.md'),path.join(folder,'开始使用.md'));
const target=path.join(root,'dist/本地文档-0.2.0-开发测试包.zip');
const result=spawnSync('/usr/bin/ditto',['-c','-k','--norsrc','--noextattr','--keepParent',folder,target],{stdio:'inherit'});
if(result.status!==0)throw new Error('Packaging failed');
const verify=path.join(staging,'unpacked');
const extracted=spawnSync('/usr/bin/ditto',['-x','-k',target,verify],{stdio:'inherit'});
if(extracted.status!==0)throw new Error('Extraction failed');
const signed=spawnSync('/usr/bin/codesign',['--verify','--deep','--strict',path.join(verify,'本地文档-0.2.0/本地文档.app')],{stdio:'inherit'});
if(signed.status!==0)throw new Error('Extracted signature failed');
const bytes=await readFile(target);
const receipt={file:target,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),extractedSignature:'PASS',nativeUI:'PENDING',chromeDelivery:'PENDING'};
await writeFile(path.join(root,'reports/stage-003/package.json'),JSON.stringify(receipt,null,2)+'\n');
await rm(staging,{recursive:true,force:true});
console.log(JSON.stringify(receipt));
